version: "3.7"

services:
  postgres-dev:
    image: postgres:15.4-bullseye
    env_file:
      - config/common.env
    container_name: postgres
    hostname: postgres
    tty: true
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./pg-catalog:/var/lib/postgresql/data
  mysql-dev:
    image: mysql:5.7
    env_file:
      - config/common.env
    container_name: mysql
    hostname: mysql
    tty: true
    ports:
      - "33067:3306"
      - "33068:33060"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./mysql-data:/var/lib/mysql
networks:
  default:
    name: database-network
    external: false