version: "3.7"

services:
  postgres-dev:
    image: postgres:15.4-bullseye
    env_file:
      - config/common.env
    container_name: postgres
    hostname: postgres
    tty: true
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg-catalog:/var/lib/postgresql/data
networks:
  default:
    name: database-network
    external: false